# Generated by Django 2.2 on 2020-12-28 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyverification', '0002_newsfavorrecord_viewerrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.FileField(null=True, upload_to='user_directory_path', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='nickname',
            field=models.CharField(max_length=32, verbose_name='昵称'),
        ),
    ]
