# Generated by Django 2.2 on 2020-12-29 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyverification', '0004_auto_20201228_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.FileField(null=True, upload_to='user_directory_path', verbose_name='头像'),
        ),
    ]
