# Generated by Django 2.2 on 2021-01-01 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keyverification', '0008_auto_20210102_0024'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userinfo',
            table='UserInfo',
        ),
    ]
