# Generated by Django 2.2 on 2021-01-07 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyverification', '0010_auto_20210103_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='title',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='标题'),
        ),
    ]
