# Generated by Django 2.2 on 2021-01-07 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyverification', '0011_news_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='user_id',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='token',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='用户Token'),
        ),
    ]
