# Generated by Django 2.2 on 2021-01-13 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyverification', '0012_auto_20210107_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='state',
            field=models.CharField(blank=True, choices=[('激活', '未激活'), ('激活', '未激活')], max_length=32, null=True, verbose_name='激活状态'),
        ),
    ]
