# Generated by Django 2.2 on 2021-01-13 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyverification', '0013_news_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='state',
            field=models.CharField(blank=True, choices=[('激活', '激活'), ('未激活', '未激活')], max_length=32, null=True, verbose_name='激活状态'),
        ),
    ]
