# Generated by Django 2.2 on 2021-01-13 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyverification', '0014_auto_20210113_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='state',
            field=models.CharField(blank=True, choices=[('true', 'false'), ('true', 'false')], max_length=32, null=True, verbose_name='激活状态'),
        ),
    ]
