# Generated by Django 2.2 on 2021-01-18 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyverification', '0015_auto_20210113_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='state',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='激活状态'),
        ),
    ]
