# Generated by Django 2.2 on 2021-01-18 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keyverification', '0016_auto_20210118_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentfavorrecord',
            name='user',
        ),
        migrations.RemoveField(
            model_name='commentrecord',
            name='user',
        ),
        migrations.RemoveField(
            model_name='news',
            name='user',
        ),
        migrations.RemoveField(
            model_name='newsfavorrecord',
            name='user',
        ),
        migrations.RemoveField(
            model_name='viewerrecord',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
