# Generated by Django 2.2 on 2021-01-18 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keyverification', '0017_auto_20210118_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=32, verbose_name='手机号')),
                ('nickname', models.CharField(max_length=32, verbose_name='昵称')),
                ('avatar', models.ImageField(null=True, upload_to='user_directory_path/%Y%m%d/', verbose_name='头像')),
                ('token', models.CharField(max_length=64, verbose_name='用户Token')),
            ],
            options={
                'db_table': 'UserInfo',
            },
        ),
        migrations.AddField(
            model_name='commentfavorrecord',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='keyverification.UserInfo', verbose_name='点赞用户'),
        ),
        migrations.AddField(
            model_name='commentrecord',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='keyverification.UserInfo', verbose_name='评论者'),
        ),
        migrations.AddField(
            model_name='news',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news', to='keyverification.UserInfo', verbose_name='发布者'),
        ),
        migrations.AddField(
            model_name='newsfavorrecord',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='keyverification.UserInfo', verbose_name='点赞用户'),
        ),
        migrations.AddField(
            model_name='viewerrecord',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='keyverification.UserInfo', verbose_name='用户'),
        ),
    ]
