# Generated by Django 2.2 on 2021-01-19 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keyverification', '0018_auto_20210118_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsdetail',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='keyverification.News', verbose_name='动态'),
        ),
    ]
