# Generated by Django 2.2 on 2021-01-29 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyverification', '0020_auto_20210128_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsdetail',
            name='key',
            field=models.CharField(max_length=128, verbose_name='腾讯对象中的文件名'),
        ),
    ]
